device_role: access_switch
default_gateway: 192.168.0.1
mgmt_vlan: 10

base_vlans:
  - { id: 10, name: MGMT }
  - { id: 20, name: USERS }
  - { id: 30, name: VOICE }

unused_interfaces:
  - GigabitEthernet0/2
  - GigabitEthernet0/3
  - GigabitEthernet1/0
  - GigabitEthernet1/1
  - GigabitEthernet1/2
  - GigabitEthernet1/3

vlans:
  - id: 40
    name: COSTUMER
    ports:
      - GigabitEthernet0/1
