ansible_network_os: cisco.ios.ios

ansible_connection: ansible.netcommon.network_cli
ansible_network_cli_ssh_type: paramiko

ansible_become: yes
ansible_become_method: enable
ansible_become_password: admin123

ansible_ssh_common_args: >-
  -o KexAlgorithms=+diffie-hellman-group1-sha1
  -o HostKeyAlgorithms=+ssh-rsa
  -o MACs=+hmac-sha1

cisco_base_config:
  - no ip domain-lookup
  - service password-encryption
  - ip domain-name lab.local
  - ip ssh version 2
  - logging buffered 10000

local_admin_user: admin
local_admin_password: admin123

dns_servers:
  - 8.8.8.8

ntp_servers:
  - 192.168.0.1

syslog_servers:
  - 192.168.0.1

logging_level: informational
