hostname: Router_PE2 
mgmt_ip: 192.168.0.14/24
mgmt_mask: 255.255.255.0

interfaces:
  - name: GigabitEthernet0/1
    ip: 10.0.14.2
    mask: 255.255.255.252

  - name: GigabitEthernet0/2
    ip: 10.2.2.1
    mask: 255.255.255.255

  - name: GigabitEthernet0/3
    ip: 10.0.24.2
    mask: 255.255.255.252

  - name: Loopback0
    ip: 10.255.0.4
    mask: 255.255.255.255

loopback_ip: 10.255.0.4
ospf_networks:
  - network: 10.255.0.4
    wildcard: 0.0.0.0
    area: 0
  - network: 10.0.14.0
    wildcard: 0.0.0.3
    area: 0
  - network: 10.0.24.0
    wildcard: 0.0.0.3
    area: 0
  - network: 10.2.2.1    # link to CE2
    wildcard: 0.0.0.3
    area: 2