#hostname: SW03
#mgmt_ip: 192.168.0.205
#mgmt_mask: 255.255.255.0

#unused_interfaces:
#  - GigabitEthernet0/3
#  - GigabitEthernet1/2
#  - GigabitEthernet1/3

#change_interface: GigabitEthernet0/2
#target_vlan_id: 40
#target_vlan_name: SERVERS
