all:
  children:
    cisco_ios:
      children:
        access_switches:
          hosts:
            sw01:
              ansible_host: 192.168.0.203
            sw02:
              ansible_host: 192.168.0.204
            sw03:
              ansible_host: 192.168.0.205

        routers:
          hosts:
            router_P1:
              ansible_host: 192.168.0.11
            router_P2:
              ansible_host: 192.168.0.12
            router_PE1:
              ansible_host: 192.168.0.13
            router_PE2:
              ansible_host: 192.168.0.14
