- name: General precheck - switches
  hosts: access_switches
  gather_facts: no

  tasks:
    - name: Check VLANs
      cisco.ios.ios_command:
        commands:
          - show vlan brief

    - name: Backup switch configs
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: backups/


- name: General precheck - routers
  hosts: routers
  gather_facts: no

  tasks:
    - name: Check interfaces
      cisco.ios.ios_command:
        commands:
          - show ip interface brief

    - name: Backup router configs
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: backups/
