- name: Show version on Cisco switches
  hosts: access_switches
  gather_facts: no

  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: show_version_output

    - name: Print show version
      ansible.builtin.debug:
        var: show_version_output.stdout_lines
