- name: Configure switches
  hosts: access_switches
  gather_facts: no
  roles:
    - role: cisco_base
      tags: [base]
    - role: access_switch
      tags: [access, vlans]

- name: Configure routers
  hosts: p_routers:pe_routers:ce_routers
  gather_facts: no
  roles:
    - role: cisco_base
      tags: [base]
    - role: router_interfaces
      tags: [interfaces]
    - role: subinterfaces
      tags: [subinterfaces]
    - role: dhcp
      tags: [dhcp]
    - role: ospf
      tags: [ospf]

- name: Configure SP Core - IS-IS
  hosts: p_routers:pe_routers
  gather_facts: no
  roles:
    - role: isis
      tags: [isis]

- name: Configure BGP
  hosts: p_routers:pe_routers:ce_routers
  gather_facts: no
  roles:
    - role: bgp
      tags: [bgp]

- name: Configure MPLS L3VPN
  hosts: pe_routers
  gather_facts: no
  roles:
    - role: mpls_l3vpn
      tags: [mpls]