- name: Post-check after VLAN change
  hosts: sw03
  gather_facts: no

  tasks:
    - name: Check interface config after change
      cisco.ios.ios_command:
        commands:
          - "show running-config interface {{ change_interface }}"
      register: interface_config_after

    - name: Check VLAN membership after change
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: vlan_table_after

    - name: Print interface config after change
      ansible.builtin.debug:
        msg: "{{ interface_config_after.stdout[0] }}"

    - name: Print VLAN table after change
      ansible.builtin.debug:
        msg: "{{ vlan_table_after.stdout[0] }}"
