name: Network CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Connect runner to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:ci
          ping: ${{ secrets.VM_HOST }}

      - name: Run Precheck + Deploy + Postcheck
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASS }}
          script: |
            cd ~/networking-ansible-lab
            git pull
            echo "=== PRECHECK ==="
            ansible-playbook playbooks/vlan_precheck.yml
            echo "=== DEPLOY ==="
            ansible-playbook playbooks/vlan_deploy.yml
            echo "=== POSTCHECK ==="
            ansible-playbook playbooks/vlan_postcheck.yml
